### ISSUE TITLE
why the blurry appearance?

### ISSUE THREAD

**Issue by devmanbr** [emilkowalski/sonner#334] opened 2024-02-13 11:18 UTC
### Describe the feature / bug 📝:
![example](https://github.com/emilkowalski/sonner/assets/67585178/eecd1e66-8452-41ad-834e-5119de6308b4)
I took this screenshot from the package website. the appearance of toasts is blurred in all cases, and it is not possible to disable this behavior (at least not completely).

I use the following code to disable this effect:
```tsx
<Toaster
toastOptions={{
style: { filter: 'blur(0)' },
}}
/>
```
however, **this code only works for the first toast**. the rest (old) remain blurred.

appearance like this, at least for me, is somewhat undesirable. There needs to be a way to disable this without having to style everything from scratch.

### Steps to reproduce the bug 🔁:
the text above makes it clear. it is default behavior.

**Comment by emilkowalski** [comment] 2024-02-15 10:41
There is no blur added to the toast, please provide a codesandbox with reproduction.

**Comment by devmanbr** [comment] 2024-02-15 13:16
I created two reproductions so you can see the difference.

this is a reproduction of the default, exactly as it appears on the [website](https://sonner.emilkowal.ski). just click the button, in the preview, to see the toast (like on the website):
https://codesandbox.io/p/sandbox/sonner-default-behavior-49hvkf

this is the same default code, just with one addition: the options that remove the filter (as I mentioned in the initial message):
https://codesandbox.io/p/sandbox/sonner-removing-blur-7mzvyg

if you place both windows side by side and click on the buttons, you will see that the last example I gave (with the options that remove the filter) has a clear appearance. in the original example (without disabling the filter) it is blurred.

if this is unintentional, it is important to find the source of the problem and fix it. if it's intentional, we should have a way to disable this behavior without having to style everything from scratch.

I'm using Windows. the problem mainly exists on Chromium-based browsers (Chrome, Edge, Opera and others). On Firefox the problem exists, but it is subtle.

**Comment by emilkowalski** [comment] 2024-02-15 13:32
I said it's not in the source code. It's likely a browser bug related to Windows as I'm unable to reproduce it on a mac. Good temporary solution could be adding `filter: 'blur(0)'` to the package itself as it's difficult to debug without the ability to reproduce. Can you provide your browser and windows versions?

**Comment by emilkowalski** [comment] 2024-02-16 09:36
Is it fixed on this preview link? https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

**Comment by andrerocco** [comment] 2024-02-17 01:41
I have also noticed this. 
@emilkowalski not fixed on this new version, at least for me. 

But I have experienced that before when using transform: translate (mostly when using percentage values). I imagine this has something to do with positioning the element in a not integer pixel values and the way the browser decides to do the rendering when that happens. But I haven't looked at any of the code so I can't be sure. 

In my experience this happens on Windows in most Chromium based browsers (it appears blurry like that in Vivaldi, Chrome, Opera but not on Firefox for example).

**Comment by emilkowalski** [comment] 2024-02-17 08:53
Can you try now @andrerocco? https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

**Comment by devmanbr** [comment] 2024-02-17 10:05
> I'm not able to reproduce on any of the sandboxes.
> 
> Like I said, nothing in the code adds a blur. It's likely a browser bug related to Windows. Good temporary solution could be adding `filter: 'blur(0)'` to the package itself as it's difficult to debug without the ability to reproduce. Can you provide your browser and windows versions?

In the current published version (1.4.0), I tested and confirmed the issue in the following environments:

**Windows 10 22H2 19045.4046:**
- Chrome 121.0.6167.185
- Edge 121.0.2277.112
- Edge Canary 123.0.2407.0
- Opera 106.0.4998.70
- Firefox 121.0.1

**Ubuntu 22.04.3:**
- Chrome 121.0.6167.184
- Firefox 119.0

as I said before, on Firefox the problem is very slight.

----------

> Can you try now @andrerocco? https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

In the provided link, **apparently it's fixed.**

**Comment by emilkowalski** [comment] 2024-02-18 09:49
Fixed in #336

**Closed by emilkowalski** 2024-02-18 09:49 UTC

**Comment by andrerocco** [comment] 2024-02-18 18:27
Fixed indeed @emilkowalski! Nice.

**Comment by andrerocco** [comment] 2024-02-18 18:31
> Can you try now @andrerocco? https://sonner-git-fix-blurry-appearance-emilkowalski-s-team.vercel.app/

Fixed indeedd @emilkowalski! Nice one. What was the fix?
